### ISSUE TITLE
How to offload to Intel integrated GPU?

### ISSUE THREAD

**Issue by pauljurczak** [numba/numba-mlir#131]
I hope it's okay to cross-post this question here (https://numba.discourse.group/t/numba-mlir-gpu-offload/1981).

I watched the presentation announced in https://numba.discourse.group/t/numba-meeting-june-6-2023-presentation-on-numba-mlir/1959/2 and installed Numba-MLIR with:
```
conda install numba-mlir -c dppy/label/dev -c intel -c conda-forge -c numba
```
A simple example:
```
from numba_mlir import njit
import numpy as np

@njit (parallel=True)
def foo(a, b):
    return a + b

result = foo(np.array([1,2,3]), np.array([4,5,6]))
print(result)
```
runs fine. There is no documentation yet and I don't know how to control where this script is run: CPU vs. GPU. What is the way to offload it to an Intel integrated GPU?

**Comment by Hardcode84** [comment]
Yes, we are unfortunately lacking documentation for GPU offload.
Some code can be found in out tests https://github.com/numba/numba-mlir/blob/main/numba_mlir/numba_mlir/mlir/tests/test_gpu.py

You will need to install `dpctl` library first  https://github.com/IntelPython/dpctl

```
conda install dpctl -c dppy/label/dev -c intel
```

And I've constructed a simple example:
```python
from numba_mlir import njit
import numba
import numpy as np
import dpctl.tensor as dpt

@njit(parallel=True)
def foo(a, b):
    return a + b

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3]])

print(a + b)

a = dpt.asarray(a, device="level_zero:gpu:0")
b = dpt.asarray(b, device="level_zero:gpu:0")

result = foo(a, b)
print(result)
```

This should offload to GPU or fail if it isn't possible.

To be really sure it was offloaded, there is an env var `NUMBA_MLIR_DUMP_IR=1` which will dump IR from various stages of compilation (few megabytes of code!, redirect to somewhere), you can grep it for `spirv` tokens.

**Comment by pauljurczak** [comment]
Thank you for prompt response. I tried this example and got:
```
[[2 4 6]
 [5 7 9]]
Traceback (most recent call last):
  File "/home/joshua/numba-mlir/m.py", line 15, in <module>
    a = dpt.asarray(a, device="level_zero:gpu:0")
  File "/home/joshua/numba-mlir/.conda/lib/python3.10/site-packages/dpctl/tensor/_ctors.py", line 574, in asarray
    sycl_queue = normalize_queue_device(
  File "/home/joshua/numba-mlir/.conda/lib/python3.10/site-packages/dpctl/tensor/_device.py", line 171, in normalize_queue_device
    d = Device.create_device(d)
  File "/home/joshua/numba-mlir/.conda/lib/python3.10/site-packages/dpctl/tensor/_device.py", line 78, in create_device
    _dev = dpctl.SyclDevice(dev)
  File "dpctl/_sycl_device.pyx", line 334, in dpctl._sycl_device.SyclDevice.__cinit__
dpctl._sycl_device.SyclDeviceCreationError: Could not create a SyclDevice with the selector string 'level_zero:gpu:0'
```
I'm running this test on Ubuntu 22.04.2 and Intel Celeron N5105 CPU, which has integrated UHD Graphics. I also have Intel GPU drivers (runtime and dev) installed following https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html.

**Comment by Hardcode84** [comment]
Can you run `sycl-ls` from this environment? Also what is the `conda list` output?

**Comment by Hardcode84** [comment]
> I don't have `sycl-ls` and not sure where to get it from.

try `conda install dpcpp_linux-64 -c intel`

**Comment by pauljurczak** [comment]
I've got:
```
(/home/joshua/numba-mlir/.conda) joshua@qvin:~/numba-mlir$ sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.15.3.0.20_160000]
[opencl:gpu:1] Intel(R) OpenCL HD Graphics, Intel(R) UHD Graphics [0x4e61] 3.0 [22.28.23726.1]
[opencl:cpu:2] Intel(R) OpenCL, Intel(R) Celeron(R) N5105 @ 2.00GHz 3.0 [2023.15.3.0.20_160000]
```

**Comment by Hardcode84** [comment]
Ok, you don't have level_zero device (some missing driver?) but still have opencl, try `device=opencl:gpu:0` or `device=opencl:gpu:0`

**Comment by pauljurczak** [comment]
Thanks. `device="opencl:gpu:0"` runs without error, but trying to get the IR fails:
```
(/home/joshua/numba-mlir/.conda) joshua@qvin:~/numba-mlir$ echo $NUMBA_MLIR_DUMP_IR
1
(/home/joshua/numba-mlir/.conda) joshua@qvin:~/numba-mlir$ python3 -m m.py
[[2 4 6]
 [5 7 9]]
Segmentation fault (core dumped)
```
IR is listed fine with the CPU example, though.

**Comment by Hardcode84** [comment]
can you add some prints around `dpt.asarray` calls? I have a feeling it didn't even get to the actual functions.

**Comment by pauljurczak** [comment]
You are right. I have:
```
print(a + b)
print('GPU part 1')
a = dpt.asarray(a, device="opencl:gpu:0")
print('GPU part 2')
b = dpt.asarray(b, device="opencl:gpu:0")
print('GPU part 3')
```
and it got only to:
```
GPU part 1
```

**Comment by pauljurczak** [comment]
I'm not 100% sure if N5105 satisfies minimum hardware requirements. Intel® oneAPI DPC++/C++ Compiler System Requirements are *Intel® UHD Graphics for 11th generation Intel processors or newer*. My UHD Graphics seems to be Gen. 11, but the CPU is Gen. 10, I think.

**Comment by diptorupd** [comment]
@pauljurczak to get the level zero drivers you can do ` conda install -c conda-forge level-zero`. After that can you post the output for the command:
`python -c "import dpctl; dpctl.lsplatform(verbosity=2)"`

**Comment by pauljurczak** [comment]
Here is the output:
```
(/home/joshua/numba-mlir/.conda) joshua@qvin:~/numba-mlir$ python -c "import dpctl; dpctl.lsplatform(verbosity=2)"
Platform  0 ::
    Name        Intel(R) FPGA Emulation Platform for OpenCL(TM)
    Version     OpenCL 1.2 Intel(R) FPGA SDK for OpenCL(TM), Version 20.3
    Vendor      Intel(R) Corporation
    Backend     opencl
    Num Devices 1
      # 0
        Name                Intel(R) FPGA Emulation Device
        Version             2023.15.3.0.20_160000
        Filter string       opencl:accelerator:0
Platform  1 ::
    Name        Intel(R) OpenCL HD Graphics
    Version     OpenCL 3.0 
    Vendor      Intel(R) Corporation
    Backend     opencl
    Num Devices 1
      # 0
        Name                Intel(R) UHD Graphics [0x4e61]
        Version             22.28.23726.1
        Filter string       opencl:gpu:0
Platform  2 ::
    Name        Intel(R) OpenCL
    Version     OpenCL 3.0 LINUX
    Vendor      Intel(R) Corporation
    Backend     opencl
    Num Devices 1
      # 0
        Name                Intel(R) Celeron(R) N5105 @ 2.00GHz
        Version             2023.15.3.0.20_160000
        Filter string       opencl:cpu:0
```

**Comment by diptorupd** [comment]
> Here is the output:
> 
Is this after installing the level-zero drivers?

**Comment by pauljurczak** [comment]
Yes.
